sudo: false
language: generic
matrix:
  include:
    - os: linux
      language: python
      python: "3.4"
    - os: linux
      language: python
      python: "3.5"
    - os: linux
      language: python
      python: "3.6"
    - os: linux
      language: python
      python: "3.6-dev"
    - os: linux
      language: python
      python: "3.7-dev"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.4.6"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.5.3"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.6.2"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.6-dev"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.7-dev"
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - env: TRAVIS_PYTHON_VERSION="3.6-dev"
    - env: TRAVIS_PYTHON_VERSION="3.7-dev"

before_install: |
  set -e
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew update
    brew install pyenv || brew upgrade pyenv
    pyenv install --list
    pyenv install "${TRAVIS_PYTHON_VERSION}"
    export PATH="$HOME/.pyenv/versions/${TRAVIS_PYTHON_VERSION}/bin:${PATH}"
  fi
  set +e

install:
  - pip install -U pip
  - pip install -U -r dev_requirements.txt

script:
  - TEST_PACKAGING=1 python -m coverage run --branch --source . -m unittest discover --verbose

after_success:
  - python -m coverage report --show-missing
  - coveralls
  - python -m pylint --load-plugins=pylint.extensions.mccabe --docstring-min-length 5 --no-docstring-rgx "^(test)?_|.*Tests$" --unsafe-load-any-extension y --output-format colorized  --reports y $(find . -name "*.py")

notifications:
  slack:
    secure: vlXI51/0L3jPt316tLvXxSgGQhlQYSxrVd0bHRYCW4iMQgxcURAlzydUO6+KJsnGQNd1wNehkIf8RMGuh7bX7siTBtRkrFdceGu2Mp69CVcX2wfZmTOvV6x3nyOUhFjDlWeaEpVg+kR2qmVSC+tJ6LLfIVRjPbcY+x/O4ubH79N1YYb6/ruqB2YK7ArY7yu+g6DcmYvb9xKMlG6KKQlAxoFywhLWkmReIvLH+mMcO+JUqez7HotMaVH8H6uwiA8NEX1FOeo1h7uXiqvtnxQcrWMZ3E/y7/W/BQEpfiy1JFGwInUN7Hs+uwevBtQx7q1/6EpTtP1xEFHKzGv/KTR5LGdeZTAw4KyL94Gifh2/+dTXG7jA9Ib4494JGduCPwTD5rbYQCgIu5fooCgJho+GJcShDNFrTwZ4AyCwPl3bpTgdUahqsM4kpp+dDfDXLiPO81ZRYFUM6h1VMM+KFNC/gLgnpt8Kz1JNPhPlBvlKu4rhFA7ULKzk0uKwS85U88+XhH3zzKi5jSDM9ejHKyNQFrHuIdkTjc+CGrc1U4/r3GlPFTjcJ0iVEftYwkTRYjAAHC/CUTsTYv5HKEY/eLYRH3R+el0p6BX9l2BIMTfJy6WXD8oyARN37ydRvkPxa1vQifG1MebMx0HxZseVcBfDOzvH9RLt5o6wMwnWkiHlm24=
  email: false
