version: "{build}"

environment:
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

matrix:
  allow_failures:
    - PYTHON: "C:\\Python34-x64"

init:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

install:
  - python -m pip install -U pip
  - python -m pip install -U -r dev_requirements.txt

build: off

test_script:
  - set TEST_PACKAGING=1
  - python -m coverage run --branch --source . -m unittest --verbose

after_test:
  - python -m coverage report --show-missing
  - codecov
